(V=[],A=[])
(V=[a],A=[])
(V=[a,b,c],A=[])
(V=[a,b,c],A=[(a,b),(b,c)])
(V=[a,b,c],A=[(a,b),(b,c),(a,c)])
(V=[a,b,c,d],A=[(a,b),(b,c),(c,d),(d,a)])
(V=[u,v,w,x,y],A=[(u,v),(u,w),(u,x),(u,y),(v,w),(v,x),(v,y),(w,x),(w,y),(x,y)])
(V=[a,b,c,d,e,f],A=[(a,d),(a,e),(a,f),(b,d),(b,e),(b,f),(c,d),(c,e),(c,f)])
